# Generated by Django 5.2.10 on 2026-03-01 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font awesome icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for category', max_length=7)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/%Y/%m/')),
                ('location', models.CharField(help_text="City, State or 'Remote'", max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('remote', 'Remote'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text="e.g., $50k - $80k or 'Competitive'", max_length=100)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements and qualifications')),
                ('application_link', models.URLField(blank=True, help_text='External application URL')),
                ('application_email', models.EmailField(blank=True, help_text='Email address for applications', max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job is currently active')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateField(blank=True, help_text='Application deadline', null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posted_date'],
                'indexes': [models.Index(fields=['-posted_date'], name='jobs_job_posted__bd758d_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'), models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx')],
            },
        ),
    ]
